/*2nd code
*How to operate the RGB LED using Arduino uno 
*(how differnt colors can be generated by mixing the values)
*
*for more detail about this project please visit:https://www.arduinounomagic.com/2019/05/how-to-control-rgb-led-using-arduino-uno.html
*
*Copyright (C) 2007 Free Software Foundation, Inc. <arduinounomagic@gmail.com>
*
*for more projects based on Arduino uno please visit:https://www.arduinounomagic.com/
*/
//intialize the PWM pins
int RED_COLOR=11;
int GREEN_COLOR=9;
int BLUE_COLOR=6;

void setup() {
 int redInput=11; //connect first pin to pin 11  
int greenInput=9;//connect third pin to pin 6  
int blueInput=6;//connect fourth pin to pin 9
}

void loop() 
{
  //generates four different colors
  analogWrite(RED_COLOR, 200); 
  analogWrite(GREEN_COLOR, 50);
  analogWrite(BLUE_COLOR, 100);
  delay(1000);
  
  analogWrite(RED_COLOR, 50);
  analogWrite(GREEN_COLOR, 200);
  analogWrite(BLUE_COLOR, 50);
  delay(1000);

  analogWrite(RED_COLOR, 0);
  analogWrite(GREEN_COLOR, 200);
  analogWrite(BLUE_COLOR, 250);
  delay(1000);

  analogWrite(RED_COLOR, 0);
  analogWrite(GREEN_COLOR, 25);
  analogWrite(BLUE_COLOR, 255);
  delay(1000);
}
